apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mqefhf0oz-nodejs 
  janus-idp.io/tekton: mqefhf0oz-nodejs
  backstage.io/kubernetes-id: mqefhf0oz-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mqefhf0oz-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  