apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mqefhf0oz-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mqefhf0oz-nodejs 
  name: mqefhf0oz-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: mqefhf0oz-nodejs 
